In [30]:
!pip install --upgrade sdv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.1/182.1 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.9/139.9 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 59.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.5/193.5 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 53.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 67.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/6

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
import zipfile
import os

zip_path = '/content/drive/MyDrive/kaggle_data/archive.zip'
extract_to = '/content/data'  # Colab 작업 공간에 압축 해제

# 압축 해제 디렉토리 생성 (없으면 자동 생성)
os.makedirs(extract_to, exist_ok=True)

# 압축 해제 실행
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

print("압축된 파일 목록:", os.listdir(extract_to))

압축된 파일 목록: ['fraudTrain.csv', 'fraudTest.csv']


In [3]:
import pandas as pd
import numpy as np
train = pd.read_csv('/content/data/fraudTrain.csv')
test = pd.read_csv('/content/data/fraudTest.csv')
print(train.shape, test.shape)

(1296675, 23) (555719, 23)


In [4]:
train.shape, test.shape

((1296675, 23), (555719, 23))

In [5]:
train.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [6]:
train = train.drop(columns=['Unnamed: 0'])
test = test.drop(columns=['Unnamed: 0'])

In [7]:
train.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0


In [8]:
missing_values = train.isnull().sum()

missing_values[missing_values > 0]

,0


In [9]:
train['is_fraud'].value_counts()

,count
is_fraud,
0,1289169
1,7506


## DROP

In [10]:
drop_cols = ['unix_time', 'trans_num', 'first', 'last', 'merchant', 'street', 'merch_lat', 'merch_long', 'city_pop', 'lat', 'long', 'zip']
train = train.drop(columns=drop_cols)

### Category

### amt

In [11]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# 로그 변환
train['amt_log'] = np.log1p(train['amt'])

# 표준화
scaler = StandardScaler()
train['amt_log_std'] = scaler.fit_transform(train[['amt_log']])

### gender

### trans_date_trans_time

In [12]:
train['datetime'] = pd.to_datetime(train['trans_date_trans_time'])

In [13]:
# 시(hour) 추출 (0~23)
train['hour'] = train['datetime'].dt.hour

# 요일 추출: Monday=0, Sunday=6
train['day_of_week'] = train['datetime'].dt.dayofweek

# 월 추출: 1월=1, 12월=12
train['month'] = train['datetime'].dt.month

#### 1. sin/cos 사용

In [14]:
train['trans_hour_sin'] = np.sin(2 * np.pi * train['hour'] / 24)
train['trans_hour_cos'] = np.cos(2 * np.pi * train['hour'] / 24)

#### 2. is_night 사용

In [15]:
train['is_night'] = train['hour'].isin([22, 23, 0, 1, 2, 3]).astype(int)

#### 3. is_high_risk_period 사용

In [16]:
# 금(4), 목(3), 수(2) + 심야 시간대(0~4, 21~23)
high_risk_days = [2, 3, 4]  # 수, 목, 금
high_risk_hours = list(range(0, 5)) + [21, 22, 23]

train['is_high_risk_period'] = (
    train['day_of_week'].isin(high_risk_days) & train['hour'].isin(high_risk_hours)
).astype(int)

### cc_num

In [17]:
from bisect import bisect_left, bisect_right

def count_past_days_fast(df, days):
    results = []
    grouped = df.groupby('cc_num')

    for card, group in grouped:
        times = group['trans_date_trans_time'].tolist()
        counts = []
        for i, t in enumerate(times):
            start_time = t - pd.Timedelta(days=days)
            # 왼쪽 경계 (start_time 이상)
            left_idx = bisect_left(times, start_time)
            # 오른쪽 경계는 현재 거래 바로 전(i번째 거래 제외)
            right_idx = i
            counts.append(right_idx - left_idx)
        results.extend(counts)
    return results

In [18]:
train['trans_date_trans_time'] = pd.to_datetime(train['trans_date_trans_time'])
train = train.sort_values(['cc_num', 'trans_date_trans_time']).reset_index(drop=True)

train['cnt_1d'] = count_past_days_fast(train, 1)
train['cnt_7d'] = count_past_days_fast(train, 7)
train['cnt_30d'] = count_past_days_fast(train, 30)

train['next_trans_time'] = train.groupby('cc_num')['trans_date_trans_time'].shift(-1)
train['time_since_last_trans'] = (train['trans_date_trans_time'] - train.groupby('cc_num')['trans_date_trans_time'].shift(1)).dt.total_seconds()

# 또는 마지막 거래 이후 경과 시간(다음 거래까지 시간 간격)
train['time_until_next_trans'] = (train['next_trans_time'] - train['trans_date_trans_time']).dt.total_seconds()

# 결측치 처리 (time_since_last_trans 첫 거래는 NaN, 0으로 채우거나 다른 방식)
train[['time_since_last_trans', 'time_until_next_trans']] = train[['time_since_last_trans', 'time_until_next_trans']].fillna(0)

### dob

#### 1. age 그대로 사용

In [19]:
train['dob'] = pd.to_datetime(train['dob'])

from dateutil.relativedelta import relativedelta

def calculate_age(born, trans_date):
    return relativedelta(trans_date, born).years

train['age'] = train.apply(lambda x: calculate_age(x['dob'], x['trans_date_trans_time']), axis=1)

#### 2. group으로 나눌 시

In [20]:
train['age_group'] = (train['age'] // 10) * 10

### job

### city-state

In [21]:
train['city_state'] = train['city'] + ', ' + train['state']

### 최종 DROP

In [22]:
drop_cols = ['trans_date_trans_time', 'dob', 'next_trans_time', 'cc_num', 'datetime', 'time_until_next_trans', 'city', 'state']
train = train.drop(columns=drop_cols)

In [23]:
train.columns

Index(['category', 'amt', 'gender', 'job', 'is_fraud', 'amt_log',
       'amt_log_std', 'hour', 'day_of_week', 'month', 'trans_hour_sin',
       'trans_hour_cos', 'is_night', 'is_high_risk_period', 'cnt_1d', 'cnt_7d',
       'cnt_30d', 'time_since_last_trans', 'age', 'age_group', 'city_state'],
      dtype='object')

In [26]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 21 columns):
 #   Column                 Non-Null Count    Dtype  
---  ------                 --------------    -----  
 0   category               1296675 non-null  object 
 1   amt                    1296675 non-null  float64
 2   gender                 1296675 non-null  object 
 3   job                    1296675 non-null  object 
 4   is_fraud               1296675 non-null  int64  
 5   amt_log                1296675 non-null  float64
 6   amt_log_std            1296675 non-null  float64
 7   hour                   1296675 non-null  int32  
 8   day_of_week            1296675 non-null  int32  
 9   month                  1296675 non-null  int32  
 10  trans_hour_sin         1296675 non-null  float64
 11  trans_hour_cos         1296675 non-null  float64
 12  is_night               1296675 non-null  int64  
 13  is_high_risk_period    1296675 non-null  int64  
 14  cnt_1d            

In [28]:
# 제거할 칼럼 리스트
cols_to_drop = ['amt', 'amt_log', 'hour', 'day_of_week', 'month', 'is_night', 'age_group']

# 제거 후 새로운 데이터프레임 생성
df = train.drop(columns=cols_to_drop)

# 결과 확인 (컬럼 수와 일부 미리보기)
print(df.shape)
df.head()

(1296675, 14)


,category,gender,job,is_fraud,amt_log_std,trans_hour_sin,trans_hour_cos,is_high_risk_period,cnt_1d,cnt_7d,cnt_30d,time_since_last_trans,age,city_state
0,misc_net,F,Information systems manager,0,-1.101895,1.224647e-16,-1.000000,0,0,0,0,0.0,32,"Fort Washakie, WY"
1,gas_transport,F,Information systems manager,0,0.352401,8.660254e-01,-0.500000,0,1,1,1,71862.0,32,"Fort Washakie, WY"
2,gas_transport,F,Information systems manager,0,0.687375,8.660254e-01,-0.500000,0,2,2,2,159.0,32,"Fort Washakie, WY"
3,kids_pets,F,Information systems manager,0,0.034277,1.224647e-16,-1.000000,0,3,3,3,13838.0,32,"Fort Washakie, WY"
4,home,F,Information systems manager,0,-0.151117,-2.588190e-01,-0.965926,0,3,4,4,1952.0,32,"Fort Washakie, WY"


In [29]:
# 1. 스무딩 인코딩 함수 정의
def target_smooth_encoding(df, column, target, smoothing):
    global_mean = df[target].mean()
    agg = df.groupby(column)[target].agg(['mean', 'count'])
    agg['smoothed'] = (
        (agg['mean'] * agg['count'] + global_mean * smoothing) /
        (agg['count'] + smoothing)
    )
    return df[column].map(agg['smoothed']).fillna(global_mean)

# 2. 'job'과 'city_state'에 대해 스무딩 인코딩 적용
df['job_enc'] = target_smooth_encoding(df, 'job', 'is_fraud', smoothing=100)
df['city_state_enc'] = target_smooth_encoding(df, 'city_state', 'is_fraud', smoothing=100)
df.head()

,category,gender,job,is_fraud,amt_log_std,trans_hour_sin,trans_hour_cos,is_high_risk_period,cnt_1d,cnt_7d,cnt_30d,time_since_last_trans,age,city_state,job_enc,city_state_enc
0,misc_net,F,Information systems manager,0,-1.101895,1.224647e-16,-1.000000,0,0,0,0,0.0,32,"Fort Washakie, WY",0.008288,0.00595
1,gas_transport,F,Information systems manager,0,0.352401,8.660254e-01,-0.500000,0,1,1,1,71862.0,32,"Fort Washakie, WY",0.008288,0.00595
2,gas_transport,F,Information systems manager,0,0.687375,8.660254e-01,-0.500000,0,2,2,2,159.0,32,"Fort Washakie, WY",0.008288,0.00595
3,kids_pets,F,Information systems manager,0,0.034277,1.224647e-16,-1.000000,0,3,3,3,13838.0,32,"Fort Washakie, WY",0.008288,0.00595
4,home,F,Information systems manager,0,-0.151117,-2.588190e-01,-0.965926,0,3,4,4,1952.0,32,"Fort Washakie, WY",0.008288,0.00595


# 증강 결과 비교

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

# 1. 평가 함수 정의
def evaluate_model(y_true, y_pred, y_proba):
    print("🔍 Classification Report:")
    print(classification_report(y_true, y_pred, digits=4))

    roc = roc_auc_score(y_true, y_proba)
    print(f"\n✅ ROC AUC: {roc}")

    cm = confusion_matrix(y_true, y_pred)
    print("📉 Confusion Matrix:")
    print(cm)

# 2. Label Encoding (category, gender)
for col in ['category', 'gender']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# 3. 사용하지 않을 컬럼 제거 (문자형 원본들)
drop_cols = ['job', 'city_state']
X = df.drop(columns=['is_fraud'] + drop_cols)
y = df['is_fraud']

# 4. 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 5. LightGBM 학습
model = LGBMClassifier(random_state=42)
model.fit(X_train, y_train)

# 6. 예측 및 평가
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

evaluate_model(y_test, y_pred, y_proba)

[LightGBM] [Info] Number of positive: 6005, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043062 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1550
[LightGBM] [Info] Number of data points in the train set: 1037340, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.005789 -> initscore=-5.146017
[LightGBM] [Info] Start training from score -5.146017
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9988    0.9986    0.9987    257834
           1     0.7705    0.7875    0.7789      1501

    accuracy                         0.9974    259335
   macro avg     0.8846    0.8931    0.8888    259335
weighted avg     0.9974    0.9974    0.9974    259335


✅ ROC AUC: 0.9481212139462428
📉 Confusion Matrix:
[[257482    352]
 [   319   1182]]


In [36]:
from sdv.single_table.ctgan import CTGAN
# 1. 평가 함수
def evaluate_model(y_true, y_pred, y_proba):
    print("🔍 Classification Report:")
    print(classification_report(y_true, y_pred, digits=4))

    roc = roc_auc_score(y_true, y_proba)
    print(f"\n✅ ROC AUC: {roc}")

    cm = confusion_matrix(y_true, y_pred)
    print("📉 Confusion Matrix:")
    print(cm)

# 2. category, gender 인코딩 (LabelEncoder → fit 저장)
le_category = LabelEncoder()
le_gender = LabelEncoder()

df['category'] = le_category.fit_transform(df['category'].astype(str))
df['gender'] = le_gender.fit_transform(df['gender'].astype(str))

# 3. 사기 거래만 추출해서 CTGAN 학습
fraud_df = df[df['is_fraud'] == 1].copy()

# 문자열로 변환 (CTGAN 요구 사항)
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

# CTGAN 학습
model = CTGAN(epochs=100)
model.fit(fraud_df, discrete_columns=['category', 'gender'])

# 4. 샘플 생성 (예: 6000건)
synthetic_fraud = model.sample(n=6000)
synthetic_fraud['is_fraud'] = 1

# 5. LabelEncoder로 다시 변환 (기존 df와 동일하게 맞추기)
synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

# 6. 기존 데이터 + 증강 데이터 병합
augmented_df = pd.concat([df, synthetic_fraud], ignore_index=True)
augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

# 7. 학습에 사용할 컬럼 정의 (문자형 제거)
drop_cols = ['is_fraud', 'job', 'city_state']  # 이미 인코딩된 버전만 사용
X = augmented_df.drop(columns=drop_cols)
y = augmented_df['is_fraud']

# 8. train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 9. LightGBM 학습
model = LGBMClassifier(random_state=42)
model.fit(X_train, y_train)

# 10. 평가
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

evaluate_model(y_test, y_pred, y_proba)

[LightGBM] [Info] Number of positive: 10805, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.079656 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2021
[LightGBM] [Info] Number of data points in the train set: 1042140, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.010368 -> initscore=-4.558600
[LightGBM] [Info] Start training from score -4.558600
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9988    0.9989    0.9988    257834
           1     0.8968    0.8812    0.8889      2701

    accuracy                         0.9977    260535
   macro avg     0.9478    0.9400    0.9439    260535
weighted avg     0.9977    0.9977    0.9977    260535


✅ ROC AUC: 0.9924351462949463
📉 Confusion Matrix:
[[257560    274]
 [   321   2380]]


In [37]:
# 2. category, gender 인코딩 (LabelEncoder → fit 저장)
le_category = LabelEncoder()
le_gender = LabelEncoder()

df['category'] = le_category.fit_transform(df['category'].astype(str))
df['gender'] = le_gender.fit_transform(df['gender'].astype(str))

# 3. 사기 거래만 추출해서 CTGAN 학습
fraud_df = df[df['is_fraud'] == 1].copy()

# 문자열로 변환 (CTGAN 요구 사항)
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

# CTGAN 학습
model = CTGAN(epochs=100)
model.fit(fraud_df, discrete_columns=['category', 'gender'])
synthetic_fraud = model.sample(n=12000)
synthetic_fraud['is_fraud'] = 1

# 5. LabelEncoder로 다시 변환 (기존 df와 동일하게 맞추기)
synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

# 6. 기존 데이터 + 증강 데이터 병합
augmented_df = pd.concat([df, synthetic_fraud], ignore_index=True)
augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

# 7. 학습에 사용할 컬럼 정의 (문자형 제거)
drop_cols = ['is_fraud', 'job', 'city_state']  # 이미 인코딩된 버전만 사용
X = augmented_df.drop(columns=drop_cols)
y = augmented_df['is_fraud']

# 8. train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 9. LightGBM 학습
model = LGBMClassifier(random_state=42)
model.fit(X_train, y_train)

# 10. 평가
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

evaluate_model(y_test, y_pred, y_proba)

[LightGBM] [Info] Number of positive: 15605, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042351 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2023
[LightGBM] [Info] Number of data points in the train set: 1046940, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.014905 -> initscore=-4.191018
[LightGBM] [Info] Start training from score -4.191018
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9986    0.9994    0.9990    257834
           1     0.9552    0.9069    0.9304      3901

    accuracy                         0.9980    261735
   macro avg     0.9769    0.9532    0.9647    261735
weighted avg     0.9979    0.9980    0.9980    261735


✅ ROC AUC: 0.9965868260221289
📉 Confusion Matrix:
[[257668    166]
 [   363   3538]]


In [38]:
# 2. category, gender 인코딩 (LabelEncoder → fit 저장)
le_category = LabelEncoder()
le_gender = LabelEncoder()

df['category'] = le_category.fit_transform(df['category'].astype(str))
df['gender'] = le_gender.fit_transform(df['gender'].astype(str))

# 3. 사기 거래만 추출해서 CTGAN 학습
fraud_df = df[df['is_fraud'] == 1].copy()

# 문자열로 변환 (CTGAN 요구 사항)
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

# CTGAN 학습
model = CTGAN(epochs=100)
model.fit(fraud_df, discrete_columns=['category', 'gender'])
synthetic_fraud = model.sample(n=24000)
synthetic_fraud['is_fraud'] = 1

# 5. LabelEncoder로 다시 변환 (기존 df와 동일하게 맞추기)
synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

# 6. 기존 데이터 + 증강 데이터 병합
augmented_df = pd.concat([df, synthetic_fraud], ignore_index=True)
augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

# 7. 학습에 사용할 컬럼 정의 (문자형 제거)
drop_cols = ['is_fraud', 'job', 'city_state']  # 이미 인코딩된 버전만 사용
X = augmented_df.drop(columns=drop_cols)
y = augmented_df['is_fraud']

# 8. train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 9. LightGBM 학습
model = LGBMClassifier(random_state=42)
model.fit(X_train, y_train)

# 10. 평가
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

evaluate_model(y_test, y_pred, y_proba)

[LightGBM] [Info] Number of positive: 25205, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.044701 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2027
[LightGBM] [Info] Number of data points in the train set: 1056540, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.023856 -> initscore=-3.711567
[LightGBM] [Info] Start training from score -3.711567
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9987    0.9995    0.9991    257834
           1     0.9771    0.9470    0.9618      6301

    accuracy                         0.9982    264135
   macro avg     0.9879    0.9732    0.9804    264135
weighted avg     0.9982    0.9982    0.9982    264135


✅ ROC AUC: 0.9990615042434187
📉 Confusion Matrix:
[[257694    140]
 [   334   5967]]


# 원본에서 증강 수 비교

In [39]:
# 2. 인코딩
df_base = df.copy()
le_category = LabelEncoder()
le_gender = LabelEncoder()

df_base['category'] = le_category.fit_transform(df_base['category'].astype(str))
df_base['gender'] = le_gender.fit_transform(df_base['gender'].astype(str))

# 3. 원본 사기 데이터만 추출해서 CTGAN 학습
fraud_df = df_base[df_base['is_fraud'] == 1].copy()
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

model = CTGAN(epochs=100)
model.fit(fraud_df, discrete_columns=['category', 'gender'])

# 4. 증강 실험 반복
for n_samples in [6000, 12000, 24000]:
    print(f"\n📊 증강 샘플 수: {n_samples}")

    # 데이터 복사
    df_copy = df_base.copy()

    # 샘플 생성
    synthetic_fraud = model.sample(n=n_samples)
    synthetic_fraud['is_fraud'] = 1

    # 인코딩 맞추기
    synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
    synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

    # 병합
    augmented_df = pd.concat([df_copy, synthetic_fraud], ignore_index=True)
    augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # 학습 준비
    X = augmented_df.drop(columns=['is_fraud', 'job', 'city_state'])
    y = augmented_df['is_fraud']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # 모델 학습
    lgbm = LGBMClassifier(random_state=42)
    lgbm.fit(X_train, y_train)

    # 평가
    y_pred = lgbm.predict(X_test)
    y_proba = lgbm.predict_proba(X_test)[:, 1]

    evaluate_model(y_test, y_pred, y_proba)


📊 증강 샘플 수: 6000
[LightGBM] [Info] Number of positive: 10805, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042460 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2021
[LightGBM] [Info] Number of data points in the train set: 1042140, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.010368 -> initscore=-4.558600
[LightGBM] [Info] Start training from score -4.558600
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9986    0.9991    0.9989    257834
           1     0.9074    0.8704    0.8885      2701

    accuracy                         0.9977    260535
   macro avg     0.9530    0.9347    0.9437    260535
weighted avg     0.9977    0.9977    0.9977    260535


✅ ROC AUC: 0.99234726985411
📉 Confusion Matrix:
[[257594    240]
 [ 

In [40]:
# 2. 인코딩
df_base = df.copy()
le_category = LabelEncoder()
le_gender = LabelEncoder()

df_base['category'] = le_category.fit_transform(df_base['category'].astype(str))
df_base['gender'] = le_gender.fit_transform(df_base['gender'].astype(str))

# 3. 원본 사기 데이터만 추출해서 CTGAN 학습
fraud_df = df_base[df_base['is_fraud'] == 1].copy()
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

model = CTGAN(epochs=300)
model.fit(fraud_df, discrete_columns=['category', 'gender'])

# 4. 증강 실험 반복
for n_samples in [6000, 12000, 24000]:
    print(f"\n📊 증강 샘플 수: {n_samples}")

    # 데이터 복사
    df_copy = df_base.copy()

    # 샘플 생성
    synthetic_fraud = model.sample(n=n_samples)
    synthetic_fraud['is_fraud'] = 1

    # 인코딩 맞추기
    synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
    synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

    # 병합
    augmented_df = pd.concat([df_copy, synthetic_fraud], ignore_index=True)
    augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # 학습 준비
    X = augmented_df.drop(columns=['is_fraud', 'job', 'city_state'])
    y = augmented_df['is_fraud']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # 모델 학습
    lgbm = LGBMClassifier(random_state=42)
    lgbm.fit(X_train, y_train)

    # 평가
    y_pred = lgbm.predict(X_test)
    y_proba = lgbm.predict_proba(X_test)[:, 1]

    evaluate_model(y_test, y_pred, y_proba)


📊 증강 샘플 수: 6000
[LightGBM] [Info] Number of positive: 10805, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.042260 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2019
[LightGBM] [Info] Number of data points in the train set: 1042140, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.010368 -> initscore=-4.558600
[LightGBM] [Info] Start training from score -4.558600
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9986    0.9992    0.9989    257834
           1     0.9186    0.8689    0.8931      2701

    accuracy                         0.9978    260535
   macro avg     0.9586    0.9341    0.9460    260535
weighted avg     0.9978    0.9978    0.9978    260535


✅ ROC AUC: 0.9929778793094639
📉 Confusion Matrix:
[[257626    208]
 

In [41]:
# 2. 인코딩
df_base = df.copy()
le_category = LabelEncoder()
le_gender = LabelEncoder()

df_base['category'] = le_category.fit_transform(df_base['category'].astype(str))
df_base['gender'] = le_gender.fit_transform(df_base['gender'].astype(str))

# 3. 원본 사기 데이터만 추출해서 CTGAN 학습
fraud_df = df_base[df_base['is_fraud'] == 1].copy()
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

model = CTGAN(epochs=300)
model.fit(fraud_df, discrete_columns=['category', 'gender'])

# 4. 증강 실험 반복
for n_samples in [35000,45000, 55000]:
    print(f"\n📊 증강 샘플 수: {n_samples}")

    # 데이터 복사
    df_copy = df_base.copy()

    # 샘플 생성
    synthetic_fraud = model.sample(n=n_samples)
    synthetic_fraud['is_fraud'] = 1

    # 인코딩 맞추기
    synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
    synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

    # 병합
    augmented_df = pd.concat([df_copy, synthetic_fraud], ignore_index=True)
    augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # 학습 준비
    X = augmented_df.drop(columns=['is_fraud', 'job', 'city_state'])
    y = augmented_df['is_fraud']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # 모델 학습
    lgbm = LGBMClassifier(random_state=42)
    lgbm.fit(X_train, y_train)

    # 평가
    y_pred = lgbm.predict(X_test)
    y_proba = lgbm.predict_proba(X_test)[:, 1]

    evaluate_model(y_test, y_pred, y_proba)


📊 증강 샘플 수: 35000
[LightGBM] [Info] Number of positive: 34005, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.076335 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2020
[LightGBM] [Info] Number of data points in the train set: 1065340, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.031919 -> initscore=-3.412102
[LightGBM] [Info] Start training from score -3.412102
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9987    0.9995    0.9991    257834
           1     0.9838    0.9591    0.9713      8501

    accuracy                         0.9982    266335
   macro avg     0.9912    0.9793    0.9852    266335
weighted avg     0.9982    0.9982    0.9982    266335


✅ ROC AUC: 0.9994697905063561
📉 Confusion Matrix:
[[257700    134]


In [42]:
# 2. 인코딩
df_base = df.copy()
le_category = LabelEncoder()
le_gender = LabelEncoder()

df_base['category'] = le_category.fit_transform(df_base['category'].astype(str))
df_base['gender'] = le_gender.fit_transform(df_base['gender'].astype(str))

# 3. 원본 사기 데이터만 추출해서 CTGAN 학습
fraud_df = df_base[df_base['is_fraud'] == 1].copy()
fraud_df['category'] = fraud_df['category'].astype(str)
fraud_df['gender'] = fraud_df['gender'].astype(str)
fraud_df = fraud_df.drop(columns=['job', 'city_state'])

model = CTGAN(epochs=300)
model.fit(fraud_df, discrete_columns=['category', 'gender'])

# 4. 증강 실험 반복
for n_samples in [65000,75000]:
    print(f"\n📊 증강 샘플 수: {n_samples}")

    # 데이터 복사
    df_copy = df_base.copy()

    # 샘플 생성
    synthetic_fraud = model.sample(n=n_samples)
    synthetic_fraud['is_fraud'] = 1

    # 인코딩 맞추기
    synthetic_fraud['category'] = le_category.transform(synthetic_fraud['category'])
    synthetic_fraud['gender'] = le_gender.transform(synthetic_fraud['gender'])

    # 병합
    augmented_df = pd.concat([df_copy, synthetic_fraud], ignore_index=True)
    augmented_df = augmented_df.sample(frac=1, random_state=42).reset_index(drop=True)

    # 학습 준비
    X = augmented_df.drop(columns=['is_fraud', 'job', 'city_state'])
    y = augmented_df['is_fraud']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # 모델 학습
    lgbm = LGBMClassifier(random_state=42)
    lgbm.fit(X_train, y_train)

    # 평가
    y_pred = lgbm.predict(X_test)
    y_proba = lgbm.predict_proba(X_test)[:, 1]

    evaluate_model(y_test, y_pred, y_proba)


📊 증강 샘플 수: 65000
[LightGBM] [Info] Number of positive: 58005, number of negative: 1031335
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.043630 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2023
[LightGBM] [Info] Number of data points in the train set: 1089340, number of used features: 13
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.053248 -> initscore=-2.878080
[LightGBM] [Info] Start training from score -2.878080
🔍 Classification Report:
              precision    recall  f1-score   support

           0     0.9985    0.9996    0.9990    257834
           1     0.9934    0.9724    0.9828     14501

    accuracy                         0.9982    272335
   macro avg     0.9959    0.9860    0.9909    272335
weighted avg     0.9982    0.9982    0.9982    272335


✅ ROC AUC: 0.9996848232111097
📉 Confusion Matrix:
[[257740     94]
